### PR TITLE
17-Exclusive-Lounge.size.speed.asm

### PR DESCRIPTION
**Pull request by chris18191**
12 cycle/ 28 lines solution

### CODE REVIEW

**Comment by atesgoral** [comment]
Thanks for this! Since this is a speed optimization, could you please rename your file to 17-Exclusive-Lounge.speed.asm? Or perhaps start from scratch and reapply your changes on top of the existing 17-Exclusive-Lounge.speed.asm for a cleaner change history?

**Comment by chris18191** [comment]
It is not only a speed optimization, but also a size optimization.
At least the games tells me it achieves both goals.
If you please could have a look:)
Tell me if I am wrong.

**Comment by atesgoral** [comment]
Ah I see now (after pasting it and running it in the game). So, this one is bang on 12/12-28/28. However, we already have a 17-Exclusive-Lounge.speed.asm with the exact same stats and there's a 17-Exclusive-Lounge.size.asm that scores 11/12. Therefore this is not exactly a size/speed improvement over what's currently available.

Having said that, we're discussing about changing the file naming paradigm to accommodate alternative implementations with same stats. It'll be nice to demonstrate different approaches.

**Comment by atesgoral** [comment]
I'll get this in and move it according to new folder structure.

**Comment by chris18191** [comment]
Oh sorry.
I did not look at them - just saw there was no *.size.speed.asm file.

**Comment by atesgoral** [comment]
Ah, you didn't have to close this. We can still get it in as it is, and I'll move it to its new home.

**Pull request merged**
