### PR TITLE
Demolishing Speed records again.

### PR DESCRIPTION
**Pull request by WolfWings**
Scavenger Chain - 20 cycles (yes, for reals)
Prime Factory - 54 cycles (yes, really)

### CODE REVIEW

**Comment by atesgoral** [comment]
Could you please rebase? Sorry about the inconvenience.

**Comment by WolfWings** [comment]
A bit messy, but rebased as requested. :)

**Comment by atesgoral** [comment]
Awesome, thanks!

**Comment by atesgoral** [comment]
OK that 54 cycle solution is worthy of a tweet my friend.

**Pull request merged**
