### PR TITLE
277 cycle solution for 40-Prime-Factory.speed.asm

### PR DESCRIPTION
**Pull request by AlanDeSmet**
Adds 277 cycle solution for floor 40: Prime Factory.

### CODE REVIEW

**Comment by atesgoral** [comment]
Could you please rebase?

**Comment by AlanDeSmet** [comment]
I believe it's all fixed up!

**Comment by WolfWings** [comment]
Sorry, I just kinda blew this one away entirely with a 54-cycle solution. >_>;

**Comment by atesgoral** [comment]
@AlanDeSmet @WolfWings I'd still like to get this in and then apply @WolfWings's crazy improvement over it. It's just nicer to capture all the work that has been done in the Git commit history.

**Pull request merged**
